version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    restart: always

volumes:
  redis-data:
    driver: local
